In [3]:
from google.colab import files
uploaded=files.upload()

Saving SQL_Sales_Dataset_200_Rows.xlsx - Sheet1.csv to SQL_Sales_Dataset_200_Rows.xlsx - Sheet1 (1).csv

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("SQL_Sales_Dataset_200_Rows.xlsx - Sheet1.csv")

In [6]:
df.head()

,order_id,customer_name,order_date,category,sub_category,product_name,quantity,unit_price,total_price,region
0,1000,Caleb Davis,2025-01-31,Clothing,Jeans,Jeans Try,2,1197,2394,West
1,1001,Misty Herrera,2025-05-05,Clothing,Jeans,Jeans New,9,1509,13581,South
2,1002,Rick Soto,2025-06-09,Clothing,Shoes,Shoes Us,5,1046,5230,East
3,1003,Sean Haas,2025-02-27,Furniture,Desk,Desk Section,10,292,2920,South
4,1004,Ann Hall,2025-06-01,Furniture,Cabinet,Cabinet Center,2,548,1096,North

In [7]:
df.tail()

,order_id,customer_name,order_date,category,sub_category,product_name,quantity,unit_price,total_price,region
195,1195,Dylan Baxter,2025-02-15,Clothing,Jeans,Jeans Sound,7,798,5586,South
196,1196,Brandon Callahan,2025-02-26,Grocery,Snacks,Snacks Lead,3,3116,9348,East
197,1197,Angela Stanton,2025-06-16,Furniture,Cabinet,Cabinet None,1,1396,1396,South
198,1198,Marissa Aguilar,2025-06-02,Grocery,Milk,Milk Listen,6,461,2766,West
199,1199,Timothy Wheeler,2025-01-29,Clothing,Shirt,Shirt Area,4,2299,9196,West

In [9]:
df.shape

(200, 10)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       200 non-null    int64
 1   customer_name  200 non-null    object
 2   order_date     200 non-null    object
 3   category       200 non-null    object
 4   sub_category   200 non-null    object
 5   product_name   200 non-null    object
 6   quantity       200 non-null    int64
 7   unit_price     200 non-null    int64
 8   total_price    200 non-null    int64
 9   region         200 non-null    object
dtypes: int64(4), object(6)
memory usage: 15.8+ KB

In [11]:
df.describe()

          order_id    quantity   unit_price   total_price
count   200.000000  200.000000   200.000000    200.000000
mean   1099.500000    4.910000  2421.495000  12100.535000
std      57.879185    3.017853  1464.016187  10915.548067
min    1000.000000    1.000000    79.000000     79.000000
25%    1049.750000    2.000000  1120.000000   3060.000000
50%    1099.500000    5.000000  2373.500000   8912.000000
75%    1149.250000    7.000000  3541.750000  19350.750000
max    1199.000000   10.000000  4997.000000  47940.000000

In [12]:
df.isnull().sum()

order_id         0
customer_name    0
order_date       0
category         0
sub_category     0
product_name     0
quantity         0
unit_price       0
total_price      0
region           0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.columns

Index(['order_id', 'customer_name', 'order_date', 'category', 'sub_category',
       'product_name', 'quantity', 'unit_price', 'total_price', 'region'],
      dtype='object')

In [16]:
df.groupby("category")["total_price"].sum()

category
Clothing       484259
Electronics    549302
Furniture      714399
Grocery        672147
Name: total_price, dtype: int64

In [17]:
df.sort_values(["category","total_price"],ascending=[True,False])

,order_id,customer_name,order_date,category,sub_category,product_name,quantity,unit_price,total_price,region
168,1168,Megan Charles,2025-03-26,Clothing,Jeans,Jeans Card,10,4462,44620,West
59,1059,Miss Rebecca Levine,2025-02-28,Clothing,Shirt,Shirt Look,6,4794,28764,East
157,1157,Patricia Gill,2025-03-23,Clothing,Jacket,Jacket Song,7,3915,27405,East
180,1180,Hailey Cobb,2025-02-19,Clothing,Jacket,Jacket Heart,6,4285,25710,East
82,1082,Kenneth Lee,2025-05-06,Clothing,Jacket,Jacket Realize,7,3486,24402,West
...,...,...,...,...,...,...,...,...,...,...
105,1105,George Hamilton,2025-06-06,Grocery,Juice,Juice Sort,10,97,970,West
141,1141,Alicia Reynolds,2025-01-10,Grocery,Snacks,Snacks Religious,1,745,745,East
192,1192,Scott Smith,2025-04-02,Grocery,Milk,Milk Factor,1,727,727,North
187,1187,Katherine Wilson,2025-05-26,Grocery,Snacks,Snacks Turn,1,500,500,South
108,1108,Joshua Myers,2025-04-14,Grocery,Snacks,Snacks Recognize,1,243,243,East

In [18]:
df.corr(numeric_only=True)

             order_id  quantity  unit_price  total_price
order_id     1.000000 -0.018182    0.102267     0.099480
quantity    -0.018182  1.000000    0.047996     0.655212
unit_price   0.102267  0.047996    1.000000     0.671318
total_price  0.099480  0.655212    0.671318     1.000000